[package]
name = "dc34-leds"
version = "0.1.0"
edition = "2021"

[dependencies]
utralib = { version = "0.1.27", optional = true, default-features = false }
xous-names = { package = "xous-api-names", version = "0.9.71" }
ticktimer = { package = "xous-api-ticktimer", version = "0.9.70" }
xous = "0.9.70"
log-server = { package = "xous-api-log", version = "0.1.69" }
log = "0.4.14"
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
bao1x-hal = { features = ["std"], optional = true, git = "https://github.com/betrusted-io/xous-core", rev = "5d5bbbfa95c0dcef26fe1fe9b496b7f6f31d191b" }
susres = { package = "xous-api-susres", git = "https://github.com/betrusted-io/xous-core", rev = "5d5bbbfa95c0dcef26fe1fe9b496b7f6f31d191b" }
bao1x-api = { git = "https://github.com/betrusted-io/xous-core", rev = "5d5bbbfa95c0dcef26fe1fe9b496b7f6f31d191b" }
bao1x-hal-service = { optional = true, git = "https://github.com/betrusted-io/xous-core", rev = "5d5bbbfa95c0dcef26fe1fe9b496b7f6f31d191b" }
usb-bao1x = { optional = true, git = "https://github.com/betrusted-io/xous-core", rev = "5d5bbbfa95c0dcef26fe1fe9b496b7f6f31d191b" }
ux-api = { optional = true, git = "https://github.com/betrusted-io/xous-core", rev = "5d5bbbfa95c0dcef26fe1fe9b496b7f6f31d191b" }
blitstr2 = { git = "https://github.com/betrusted-io/xous-core", rev = "5d5bbbfa95c0dcef26fe1fe9b496b7f6f31d191b", features = ["bao1x"] }
arbitrary-int = "1.2"
getrandom = "=0.2.12"

[patch.crates-io.getrandom]
git = "https://github.com/betrusted-io/xous-core"
rev = "5d5bbbfa95c0dcef26fe1fe9b496b7f6f31d191b"

[patch."https://github.com/betrusted-io/xous-core"]
bao1x-hal = { path = "../xous-core/libs/bao1x-hal" }
xous-api-susres = { path = "../xous-core/api/xous-api-susres" }
bao1x-hal-service = { path = "../xous-core/services/bao1x-hal-service" }
bao1x-api = { path = "../xous-core/libs/bao1x-api" }
ux-api = { path = "../xous-core/libs/ux-api" }
usb-bao1x = { path = "../xous-core/services/usb-bao1x" }
blitstr2 = { path = "../xous-core/libs/blitstr2" }

[profile.release]
codegen-units = 1
debug = false
strip = false
lto = "fat"
incremental = true
opt-level = "s"

[features]
bao1x = ["utralib/bao1x", "usb-bao1x?/bao1x"]
board-baosec = ["bao1x-hal-service", "bao1x-hal", "usb-bao1x", "usb-bao1x/board-baosec", "ux-api/board-baosec", "bao1x-hal/board-baosec", "blitstr2/board-baosec"]
oem-baosec-lite = ["bao1x-hal/sensor-lis2dh12", "usb-bao1x?/oem-baosec-lite"]
default = ["oem-baosec-lite"]
