// AUTOGENERATED CODE on 2026-08-08T10:21:47.083117 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(breathing_bio_code, BM_BREATHING_BIO_START, BM_BREATHING_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	33f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // ws2812c_wfi: @ws2812c_wfi
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // main: @main
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "li	a3, 0",
    // --- inline asm begin ---
    "mv	x27, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "lui	a1, %hi(50f)",
    "sw	a0, %lo(50f)(a1)",
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "li	a2, 16",
    "addi	a1, a1, %lo(50f)",
    "bltu	a0, a2, 34f",
    "li	a0, 16",
    "34:", // .LBB3_2
    "sw	a0, 4(a1)",
    "li	s0, 18",
    "35:", // .LBB3_3: =>This Loop Header: Depth=1
    // Child Loop BB3_4 Depth 2
    // Child Loop BB3_5 Depth 3
    // Child Loop BB3_8 Depth 2
    // Child Loop BB3_13 Depth 2
    // Child Loop BB3_14 Depth 3
    // Child Loop BB3_15 Depth 4
    // Child Loop BB3_18 Depth 3
    "slli	a0, a3, 5",
    "mv	s1, a3",
    "slli	a1, a3, 8",
    "sub	a0, a1, a0",
    "srli	a0, a0, 6",
    "jal	ra, 47f",
    "li	a0, 0",
    "36:", // .LBB3_4: Parent Loop BB3_3 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_5 Depth 3
    "li	a1, 667",
    "37:", // .LBB3_5: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_4 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 37b",
    // in Loop: Header=BB3_4 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, s0, 36b",
    // in Loop: Header=BB3_3 Depth=1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "li	a1, 1",
    "mv	a3, s1",
    "bgez	a0, 40f",
    "38:", // .LBB3_8: Parent Loop BB3_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 39f",
    // in Loop: Header=BB3_8 Depth=2
    // --- inline asm begin ---
    "mv	x18, a1",
    // --- inline asm end ---
    "39:", // .LBB3_10: in Loop: Header=BB3_8 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 38b",
    "40:", // .LBB3_11: in Loop: Header=BB3_3 Depth=1
    "addi	a3, a3, 1",
    "li	a0, 65",
    "bne	a3, a0, 35b",
    // in Loop: Header=BB3_3 Depth=1
    "li	s1, 64",
    "41:", // .LBB3_13: Parent Loop BB3_3 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_14 Depth 3
    // Child Loop BB3_15 Depth 4
    // Child Loop BB3_18 Depth 3
    "slli	a0, s1, 5",
    "slli	a1, s1, 8",
    "sub	a0, a1, a0",
    "srli	a0, a0, 6",
    "jal	ra, 47f",
    "li	a0, 0",
    "42:", // .LBB3_14: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_13 Depth=2
    // =>    This Loop Header: Depth=3
    // Child Loop BB3_15 Depth 4
    "li	a1, 667",
    "43:", // .LBB3_15: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_13 Depth=2
    // Parent Loop BB3_14 Depth=3
    // =>      This Inner Loop Header: Depth=4
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 43b",
    // in Loop: Header=BB3_14 Depth=3
    "addi	a0, a0, 1",
    "bne	a0, s0, 42b",
    // in Loop: Header=BB3_13 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "li	a1, 1",
    "bgez	a0, 46f",
    "44:", // .LBB3_18: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_13 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 45f",
    // in Loop: Header=BB3_18 Depth=3
    // --- inline asm begin ---
    "mv	x18, a1",
    // --- inline asm end ---
    "45:", // .LBB3_20: in Loop: Header=BB3_18 Depth=3
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 44b",
    "46:", // .LBB3_21: in Loop: Header=BB3_13 Depth=2
    "addi	s1, s1, -1",
    "bnez	s1, 41b",
    // in Loop: Header=BB3_3 Depth=1
    "li	a3, 0",
    "j	35b",
    "47:", // show_level: @show_level
    "lui	a1, %hi(50f)",
    "addi	a1, a1, %lo(50f)",
    "lw	a2, 4(a1)",
    "beqz	a2, 49f",
    "mul	a0, a0, a0",
    "srli	a3, a0, 8",
    "andi	a0, a0, -256",
    "sub	a0, a0, a3",
    "slli	a4, a3, 14",
    "slli	a3, a3, 16",
    "sub	a3, a3, a4",
    "lui	a4, 1048560",
    "and	a3, a3, a4",
    "slli	a4, a2, 2",
    "addi	a1, a1, 8",
    "srli	a0, a0, 8",
    "or	a0, a0, a3",
    "add	a3, a1, a4",
    "48:", // .LBB4_2: =>This Inner Loop Header: Depth=1
    "sw	a0, 0(a1)",
    "addi	a1, a1, 4",
    "bne	a1, a3, 48b",
    "49:", // .LBB4_3
    "lui	a1, %hi(50f)",
    "lw	a0, %lo(50f)(a1)",
    "addi	a1, a1, %lo(50f)",
    "addi	a1, a1, 8",
    "jal	zero, 21b",
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "50:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_count (4 entries, 1 words) ---
    ".p2align 0",
    "51:", // led_count
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_buf (64 entries, 16 words) ---
    ".p2align 0",
    "52:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000" // [60] 0, 0, 0, 0
);
