// AUTOGENERATED CODE on 2026-08-08T10:21:49.463374 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(brrunner_bio_code, BM_BRRUNNER_BIO_START, BM_BRRUNNER_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	33f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // ws2812c_wfi: @ws2812c_wfi
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // main: @main
    "addi	sp, sp, -32",
    "sw	ra, 28(sp)", // 4-byte Folded Spill
    "sw	s0, 24(sp)", // 4-byte Folded Spill
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    "li	a0, 0",
    // --- inline asm begin ---
    "mv	x27, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a1, x17",
    // --- inline asm end ---
    "lui	a2, %hi(51f)",
    "sw	a1, %lo(51f)(a2)",
    // --- inline asm begin ---
    "mv	s1, x17",
    // --- inline asm end ---
    "li	a1, 16",
    "addi	a2, a2, %lo(51f)",
    "bltu	s1, a1, 34f",
    "li	s1, 16",
    "34:", // .LBB3_2
    "sw	s1, 4(a2)",
    "addi	a2, a2, 8",
    "sw	a2, 12(sp)", // 4-byte Folded Spill
    "lui	a1, %hi(51f)",
    "addi	a1, a1, %lo(51f)",
    "addi	a1, a1, 8",
    "sw	a1, 8(sp)", // 4-byte Folded Spill
    "beqz	s1, 37f",
    "35:", // .LBB3_3
    "slli	a2, s1, 2",
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    "add	a2, a2, a1",
    "36:", // .LBB3_4: =>This Inner Loop Header: Depth=1
    "sw	zero, 0(a1)",
    "addi	a1, a1, 4",
    "bne	a1, a2, 36b",
    "37:", // .LBB3_5: =>This Loop Header: Depth=1
    // Child Loop BB3_6 Depth 2
    // Child Loop BB3_8 Depth 2
    // Child Loop BB3_9 Depth 3
    // Child Loop BB3_12 Depth 2
    "add	s0, a0, s1",
    "addi	s0, s0, 5",
    "38:", // .LBB3_6: Parent Loop BB3_5 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "sub	s0, s0, s1",
    "bge	s0, s1, 38b",
    // in Loop: Header=BB3_5 Depth=1
    "li	a1, 255",
    "li	a2, 192",
    "sw	a0, 16(sp)", // 4-byte Folded Spill
    "li	a3, 0",
    "jal	ra, 44f",
    "li	a2, 255",
    "li	a3, 20",
    "mv	a0, s0",
    "li	a1, 0",
    "jal	ra, 44f",
    "lui	a0, %hi(51f)",
    "lw	a0, %lo(51f)(a0)",
    "lw	a1, 12(sp)", // 4-byte Folded Reload
    "mv	a2, s1",
    "jal	ra, 21b",
    "li	a0, 0",
    "li	a2, 60",
    "39:", // .LBB3_8: Parent Loop BB3_5 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_9 Depth 3
    "li	a1, 667",
    "40:", // .LBB3_9: Parent Loop BB3_5 Depth=1
    // Parent Loop BB3_8 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 40b",
    // in Loop: Header=BB3_8 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, a2, 39b",
    // in Loop: Header=BB3_5 Depth=1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "lw	a1, 16(sp)", // 4-byte Folded Reload
    "li	a2, 1",
    "bgez	a0, 43f",
    "41:", // .LBB3_12: Parent Loop BB3_5 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 42f",
    // in Loop: Header=BB3_12 Depth=2
    // --- inline asm begin ---
    "mv	x18, a2",
    // --- inline asm end ---
    "42:", // .LBB3_14: in Loop: Header=BB3_12 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 41b",
    "43:", // .LBB3_15: in Loop: Header=BB3_5 Depth=1
    "lui	a0, %hi(51f)",
    "addi	a0, a0, %lo(51f)",
    "lw	s1, 4(a0)",
    "addi	a0, a1, 1",
    "slt	a1, a0, s1",
    "neg	a1, a1",
    "and	a0, a0, a1",
    "bnez	s1, 35b",
    "j	37b",
    "44:", // draw_comet: @draw_comet
    "addi	sp, sp, -32",
    "sw	ra, 28(sp)", // 4-byte Folded Spill
    "sw	s0, 24(sp)", // 4-byte Folded Spill
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    "sw	a3, 16(sp)", // 4-byte Folded Spill
    "sw	a2, 12(sp)", // 4-byte Folded Spill
    "sw	a1, 8(sp)", // 4-byte Folded Spill
    "mv	a1, a0",
    "li	a4, 0",
    "lui	a0, %hi(51f)",
    "addi	a0, a0, %lo(51f)",
    "lw	a5, 4(a0)",
    "mv	a0, a1",
    "li	t2, 255",
    "45:", // .LBB4_1: =>This Loop Header: Depth=1
    // Child Loop BB4_3 Depth 2
    "sub	s0, a1, a4",
    "bgez	s0, 47f",
    // in Loop: Header=BB4_1 Depth=1
    "mv	s0, a0",
    "46:", // .LBB4_3: Parent Loop BB4_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "add	s0, s0, a5",
    "bltz	s0, 46b",
    "47:", // .LBB4_4: in Loop: Header=BB4_1 Depth=1
    "slli	s0, s0, 2",
    "lui	ra, %hi(51f)",
    "addi	ra, ra, %lo(51f)",
    "add	ra, ra, s0",
    "lw	t0, 8(ra)",
    "li	a2, 255",
    "srl	t1, a2, a4",
    "lw	a2, 8(sp)", // 4-byte Folded Reload
    "mul	a3, t1, a2",
    "srli	a3, a3, 8",
    "slli	s1, t0, 16",
    "srli	s1, s1, 24",
    "add	s1, s1, a3",
    "bltu	s1, t2, 48f",
    // in Loop: Header=BB4_1 Depth=1
    "li	s1, 255",
    "48:", // .LBB4_6: in Loop: Header=BB4_1 Depth=1
    "lw	a2, 12(sp)", // 4-byte Folded Reload
    "mul	a3, t1, a2",
    "slli	s0, t0, 8",
    "srli	a3, a3, 8",
    "srli	s0, s0, 24",
    "add	s0, s0, a3",
    "bltu	s0, t2, 49f",
    // in Loop: Header=BB4_1 Depth=1
    "li	s0, 255",
    "49:", // .LBB4_8: in Loop: Header=BB4_1 Depth=1
    "lw	a2, 16(sp)", // 4-byte Folded Reload
    "mul	a3, t1, a2",
    "srli	a2, a3, 8",
    "zext.b	a3, t0",
    "add	a3, a3, a2",
    "bltu	a3, t2, 50f",
    // in Loop: Header=BB4_1 Depth=1
    "li	a3, 255",
    "50:", // .LBB4_10: in Loop: Header=BB4_1 Depth=1
    "slli	s0, s0, 16",
    "slli	s1, s1, 8",
    "addi	a4, a4, 1",
    "or	s0, s0, s1",
    "or	a3, a3, s0",
    "sw	a3, 8(ra)",
    "addi	a0, a0, -1",
    "li	a2, 4",
    "bne	a4, a2, 45b",
    "lw	ra, 28(sp)", // 4-byte Folded Reload
    "lw	s0, 24(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	s1, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw s1, 24(sp)",
    "addi sp, sp, 4",
    "addi	sp, sp, 32",
    "ret",
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "51:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_count (4 entries, 1 words) ---
    ".p2align 0",
    "52:", // led_count
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_buf (64 entries, 16 words) ---
    ".p2align 0",
    "53:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000" // [60] 0, 0, 0, 0
);
