// AUTOGENERATED CODE on 2026-08-08T10:21:44.699938 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(cylon_bio_code, BM_CYLON_BIO_START, BM_CYLON_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	33f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // ws2812c_wfi: @ws2812c_wfi
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // main: @main
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "li	a0, 0",
    // --- inline asm begin ---
    "mv	x27, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "lui	a1, %hi(52f)",
    "sw	a0, %lo(52f)(a1)",
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "li	a2, 16",
    "addi	a1, a1, %lo(52f)",
    "bltu	a0, a2, 34f",
    "li	a0, 16",
    "34:", // .LBB3_2
    "sw	a0, 4(a1)",
    "li	s1, 55",
    "35:", // .LBB3_3: =>This Loop Header: Depth=1
    // Child Loop BB3_5 Depth 2
    // Child Loop BB3_6 Depth 3
    // Child Loop BB3_7 Depth 4
    // Child Loop BB3_10 Depth 3
    // Child Loop BB3_16 Depth 2
    // Child Loop BB3_17 Depth 3
    // Child Loop BB3_18 Depth 4
    // Child Loop BB3_21 Depth 3
    "blez	a0, 35b",
    // in Loop: Header=BB3_3 Depth=1
    "li	s0, 0",
    "36:", // .LBB3_5: Parent Loop BB3_3 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_6 Depth 3
    // Child Loop BB3_7 Depth 4
    // Child Loop BB3_10 Depth 3
    "mv	a0, s0",
    "jal	ra, 48f",
    "li	a0, 0",
    "37:", // .LBB3_6: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_5 Depth=2
    // =>    This Loop Header: Depth=3
    // Child Loop BB3_7 Depth 4
    "li	a1, 667",
    "38:", // .LBB3_7: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_5 Depth=2
    // Parent Loop BB3_6 Depth=3
    // =>      This Inner Loop Header: Depth=4
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 38b",
    // in Loop: Header=BB3_6 Depth=3
    "addi	a0, a0, 1",
    "bne	a0, s1, 37b",
    // in Loop: Header=BB3_5 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "li	a1, 1",
    "bgez	a0, 41f",
    "39:", // .LBB3_10: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_5 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 40f",
    // in Loop: Header=BB3_10 Depth=3
    // --- inline asm begin ---
    "mv	x18, a1",
    // --- inline asm end ---
    "40:", // .LBB3_12: in Loop: Header=BB3_10 Depth=3
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 39b",
    "41:", // .LBB3_13: in Loop: Header=BB3_5 Depth=2
    "lui	a0, %hi(53f)",
    "lw	a0, %lo(53f)(a0)",
    "addi	s0, s0, 1",
    "blt	s0, a0, 36b",
    // in Loop: Header=BB3_3 Depth=1
    "li	a1, 3",
    "blt	a0, a1, 35b",
    // in Loop: Header=BB3_3 Depth=1
    "addi	a0, a0, -2",
    "42:", // .LBB3_16: Parent Loop BB3_3 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_17 Depth 3
    // Child Loop BB3_18 Depth 4
    // Child Loop BB3_21 Depth 3
    "mv	s0, a0",
    "jal	ra, 48f",
    "li	a0, 0",
    "43:", // .LBB3_17: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_16 Depth=2
    // =>    This Loop Header: Depth=3
    // Child Loop BB3_18 Depth 4
    "li	a1, 667",
    "44:", // .LBB3_18: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_16 Depth=2
    // Parent Loop BB3_17 Depth=3
    // =>      This Inner Loop Header: Depth=4
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 44b",
    // in Loop: Header=BB3_17 Depth=3
    "addi	a0, a0, 1",
    "bne	a0, s1, 43b",
    // in Loop: Header=BB3_16 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "li	a1, 1",
    "bgez	a0, 47f",
    "45:", // .LBB3_21: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_16 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 46f",
    // in Loop: Header=BB3_21 Depth=3
    // --- inline asm begin ---
    "mv	x18, a1",
    // --- inline asm end ---
    "46:", // .LBB3_23: in Loop: Header=BB3_21 Depth=3
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 45b",
    "47:", // .LBB3_24: in Loop: Header=BB3_16 Depth=2
    "addi	a0, s0, -1",
    "blt	a1, s0, 42b",
    // in Loop: Header=BB3_3 Depth=1
    "lui	a0, %hi(53f)",
    "lw	a0, %lo(53f)(a0)",
    "j	35b",
    "48:", // show_head: @show_head
    "lui	a1, %hi(52f)",
    "addi	a1, a1, %lo(52f)",
    "lw	a2, 4(a1)",
    "beqz	a2, 51f",
    "neg	a3, a0",
    "slli	t0, a2, 2",
    "addi	a1, a1, 8",
    "lui	a4, 16",
    "add	t0, t0, a1",
    "addi	t1, a4, -256",
    "49:", // .LBB4_2: =>This Inner Loop Header: Depth=1
    "li	a5, 255",
    "beqz	a3, 50f",
    // in Loop: Header=BB4_2 Depth=1
    "srai	a4, a3, 31",
    "xor	a0, a3, a4",
    "sub	a0, a0, a4",
    "sltiu	a4, a0, 5",
    "srl	a0, a5, a0",
    "neg	a5, a4",
    "and	a5, a5, a0",
    "50:", // .LBB4_4: in Loop: Header=BB4_2 Depth=1
    "slli	a0, a5, 8",
    "sub	a0, a0, a5",
    "andi	a4, a5, 240",
    "slli	a4, a4, 12",
    "and	a0, a0, t1",
    "or	a0, a0, a4",
    "sw	a0, 0(a1)",
    "addi	a1, a1, 4",
    "addi	a3, a3, 1",
    "bne	a1, t0, 49b",
    "51:", // .LBB4_5
    "lui	a1, %hi(52f)",
    "lw	a0, %lo(52f)(a1)",
    "addi	a1, a1, %lo(52f)",
    "addi	a1, a1, 8",
    "jal	zero, 21b",
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "52:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_count (4 entries, 1 words) ---
    ".p2align 0",
    "53:", // led_count
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_buf (64 entries, 16 words) ---
    ".p2align 0",
    "54:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000" // [60] 0, 0, 0, 0
);
