// AUTOGENERATED CODE on 2026-08-12T19:11:43.047011 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(cylon_bio_code, BM_CYLON_BIO_START, BM_CYLON_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	33f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // ws2812c_wfi: @ws2812c_wfi
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // main: @main
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "li	a0, 0",
    // --- inline asm begin ---
    "mv	x27, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "lui	a1, %hi(52f)",
    "sw	a0, %lo(52f)(a1)",
    "addi	a1, a1, %lo(52f)",
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "sw	a0, 4(a1)",
    // --- inline asm begin ---
    "mv	a2, x17",
    // --- inline asm end ---
    "li	a0, 255",
    "bltu	a2, a0, 34f",
    "li	a2, 255",
    "34:", // .LBB3_2
    "lw	a0, 4(a1)",
    "sw	a2, 8(a1)",
    "li	a1, 17",
    "bltu	a0, a1, 35f",
    "li	a0, 16",
    "lui	a1, %hi(53f)",
    "sw	a0, %lo(53f)(a1)",
    "35:", // .LBB3_4
    "li	s1, 55",
    "36:", // .LBB3_5: =>This Loop Header: Depth=1
    // Child Loop BB3_7 Depth 2
    // Child Loop BB3_8 Depth 3
    // Child Loop BB3_9 Depth 4
    // Child Loop BB3_14 Depth 2
    // Child Loop BB3_15 Depth 3
    // Child Loop BB3_16 Depth 4
    "blez	a0, 36b",
    // in Loop: Header=BB3_5 Depth=1
    "li	s0, 0",
    "37:", // .LBB3_7: Parent Loop BB3_5 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_8 Depth 3
    // Child Loop BB3_9 Depth 4
    "mv	a0, s0",
    "jal	ra, 43f",
    "li	a0, 0",
    "38:", // .LBB3_8: Parent Loop BB3_5 Depth=1
    // Parent Loop BB3_7 Depth=2
    // =>    This Loop Header: Depth=3
    // Child Loop BB3_9 Depth 4
    "li	a1, 667",
    "39:", // .LBB3_9: Parent Loop BB3_5 Depth=1
    // Parent Loop BB3_7 Depth=2
    // Parent Loop BB3_8 Depth=3
    // =>      This Inner Loop Header: Depth=4
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 39b",
    // in Loop: Header=BB3_8 Depth=3
    "addi	a0, a0, 1",
    "bne	a0, s1, 38b",
    // in Loop: Header=BB3_7 Depth=2
    "jal	ra, 47f",
    "lui	a0, %hi(53f)",
    "lw	a0, %lo(53f)(a0)",
    "addi	s0, s0, 1",
    "blt	s0, a0, 37b",
    // in Loop: Header=BB3_5 Depth=1
    "li	a1, 3",
    "blt	a0, a1, 36b",
    // in Loop: Header=BB3_5 Depth=1
    "addi	a0, a0, -2",
    "40:", // .LBB3_14: Parent Loop BB3_5 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_15 Depth 3
    // Child Loop BB3_16 Depth 4
    "mv	s0, a0",
    "jal	ra, 43f",
    "li	a0, 0",
    "41:", // .LBB3_15: Parent Loop BB3_5 Depth=1
    // Parent Loop BB3_14 Depth=2
    // =>    This Loop Header: Depth=3
    // Child Loop BB3_16 Depth 4
    "li	a1, 667",
    "42:", // .LBB3_16: Parent Loop BB3_5 Depth=1
    // Parent Loop BB3_14 Depth=2
    // Parent Loop BB3_15 Depth=3
    // =>      This Inner Loop Header: Depth=4
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 42b",
    // in Loop: Header=BB3_15 Depth=3
    "addi	a0, a0, 1",
    "bne	a0, s1, 41b",
    // in Loop: Header=BB3_14 Depth=2
    "jal	ra, 47f",
    "addi	a0, s0, -1",
    "li	a1, 1",
    "blt	a1, s0, 40b",
    // in Loop: Header=BB3_5 Depth=1
    "lui	a0, %hi(53f)",
    "lw	a0, %lo(53f)(a0)",
    "j	36b",
    "43:", // show_head: @show_head
    "lui	a3, %hi(52f)",
    "addi	a3, a3, %lo(52f)",
    "lw	a2, 4(a3)",
    "beqz	a2, 46f",
    "lw	a1, 8(a3)",
    "neg	a4, a0",
    "slli	t0, a2, 2",
    "addi	a3, a3, 12",
    "add	t0, t0, a3",
    "44:", // .LBB4_2: =>This Inner Loop Header: Depth=1
    "mv	a5, a1",
    "beqz	a4, 45f",
    // in Loop: Header=BB4_2 Depth=1
    "srai	a5, a4, 31",
    "xor	a0, a4, a5",
    "sub	a0, a0, a5",
    "sltiu	a5, a0, 5",
    "srl	a0, a1, a0",
    "neg	a5, a5",
    "and	a5, a5, a0",
    "45:", // .LBB4_4: in Loop: Header=BB4_2 Depth=1
    "slli	a0, a5, 8",
    "sub	a0, a0, a5",
    "srli	a5, a5, 4",
    "slli	a5, a5, 16",
    "andi	a0, a0, -256",
    "or	a0, a0, a5",
    "sw	a0, 0(a3)",
    "addi	a3, a3, 4",
    "addi	a4, a4, 1",
    "bne	a3, t0, 44b",
    "46:", // .LBB4_5
    "lui	a1, %hi(52f)",
    "lw	a0, %lo(52f)(a1)",
    "addi	a1, a1, %lo(52f)",
    "addi	a1, a1, 12",
    "jal	zero, 21b",
    "47:", // drain_fifo1: @drain_fifo1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bgez	a0, 51f",
    "lui	a0, %hi(54f)",
    "li	a1, 1",
    "48:", // .LBB5_2: =>This Inner Loop Header: Depth=1
    // --- inline asm begin ---
    "mv	a2, x17",
    // --- inline asm end ---
    "bltz	a2, 49f",
    // in Loop: Header=BB5_2 Depth=1
    "srli	a3, a2, 30",
    "beqz	a3, 50f",
    // in Loop: Header=BB5_2 Depth=1
    "zext.b	a2, a2",
    "sw	a2, %lo(54f)(a0)",
    "j	50f",
    "49:", // .LBB5_5: in Loop: Header=BB5_2 Depth=1
    // --- inline asm begin ---
    "mv	x18, a1",
    // --- inline asm end ---
    "50:", // .LBB5_6: in Loop: Header=BB5_2 Depth=1
    // --- inline asm begin ---
    "mv	a2, x30",
    // --- inline asm end ---
    "slli	a2, a2, 5",
    "bltz	a2, 48b",
    "51:", // .LBB5_7
    "ret",
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "52:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_count (4 entries, 1 words) ---
    ".p2align 0",
    "53:", // led_count
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: brightness (4 entries, 1 words) ---
    ".p2align 0",
    "54:", // brightness
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_buf (64 entries, 16 words) ---
    ".p2align 0",
    "55:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000" // [60] 0, 0, 0, 0
);
