// AUTOGENERATED CODE on 2026-08-12T19:11:42.272622 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(police_bio_code, BM_POLICE_BIO_START, BM_POLICE_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	33f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // ws2812c_wfi: @ws2812c_wfi
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // main: @main
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "li	a0, 0",
    // --- inline asm begin ---
    "mv	x27, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "lui	a1, %hi(59f)",
    "sw	a0, %lo(59f)(a1)",
    "addi	a0, a1, %lo(59f)",
    // --- inline asm begin ---
    "mv	a1, x17",
    // --- inline asm end ---
    "sw	a1, 4(a0)",
    // --- inline asm begin ---
    "mv	a1, x17",
    // --- inline asm end ---
    "li	a2, 255",
    "bltu	a1, a2, 34f",
    "li	a1, 255",
    "34:", // .LBB3_2
    "lw	a2, 4(a0)",
    "li	a3, 17",
    "sw	a1, 8(a0)",
    "bltu	a2, a3, 35f",
    "lui	a0, %hi(60f)",
    "li	a1, 16",
    "sw	a1, %lo(60f)(a0)",
    "35:", // .LBB3_4
    "jal	ra, 41f",
    "li	s0, 90",
    "36:", // .LBB3_5: =>This Loop Header: Depth=1
    // Child Loop BB3_6 Depth 2
    // Child Loop BB3_7 Depth 3
    // Child Loop BB3_10 Depth 2
    // Child Loop BB3_11 Depth 3
    "li	a0, 0",
    "jal	ra, 44f",
    "li	a0, 0",
    "37:", // .LBB3_6: Parent Loop BB3_5 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_7 Depth 3
    "li	a1, 667",
    "38:", // .LBB3_7: Parent Loop BB3_5 Depth=1
    // Parent Loop BB3_6 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 38b",
    // in Loop: Header=BB3_6 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, s0, 37b",
    // in Loop: Header=BB3_5 Depth=1
    "jal	ra, 54f",
    "li	a0, 1",
    "jal	ra, 44f",
    "li	a0, 0",
    "39:", // .LBB3_10: Parent Loop BB3_5 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_11 Depth 3
    "li	a1, 667",
    "40:", // .LBB3_11: Parent Loop BB3_5 Depth=1
    // Parent Loop BB3_10 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 40b",
    // in Loop: Header=BB3_10 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, s0, 39b",
    // in Loop: Header=BB3_5 Depth=1
    "jal	ra, 54f",
    "j	36b",
    "41:", // blank: @blank
    "lui	a0, %hi(59f)",
    "addi	a0, a0, %lo(59f)",
    "lw	a2, 4(a0)",
    "beqz	a2, 43f",
    "slli	a1, a2, 2",
    "addi	a0, a0, 12",
    "add	a1, a1, a0",
    "42:", // .LBB4_2: =>This Inner Loop Header: Depth=1
    "sw	zero, 0(a0)",
    "addi	a0, a0, 4",
    "bne	a0, a1, 42b",
    "43:", // .LBB4_3
    "lui	a1, %hi(59f)",
    "lw	a0, %lo(59f)(a1)",
    "addi	a1, a1, %lo(59f)",
    "addi	a1, a1, 12",
    "jal	zero, 21b",
    "44:", // burst: @burst
    "addi	sp, sp, -32",
    "sw	ra, 28(sp)", // 4-byte Folded Spill
    "sw	s0, 24(sp)", // 4-byte Folded Spill
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    "mv	s0, a0",
    "li	a2, 0",
    "lui	a3, %hi(59f)",
    "addi	a3, a3, %lo(59f)",
    "lui	a1, %hi(59f)",
    "lui	a0, 11",
    "addi	a1, a1, %lo(59f)",
    "addi	a4, a3, 12",
    "sw	a4, 8(sp)", // 4-byte Folded Spill
    "addi	a1, a1, 12",
    "sw	a1, 12(sp)", // 4-byte Folded Spill
    "addi	s1, a0, -1366",
    "45:", // .LBB5_1: =>This Loop Header: Depth=1
    // Child Loop BB5_6 Depth 2
    // Child Loop BB5_8 Depth 2
    // Child Loop BB5_9 Depth 3
    // Child Loop BB5_12 Depth 2
    // Child Loop BB5_13 Depth 3
    "lw	a0, 8(a3)",
    "slli	a1, a0, 8",
    "sub	a0, a1, a0",
    "sw	a2, 16(sp)", // 4-byte Folded Spill
    "beqz	s0, 46f",
    // in Loop: Header=BB5_1 Depth=1
    "srli	a0, a0, 8",
    "j	47f",
    "46:", // .LBB5_3: in Loop: Header=BB5_1 Depth=1
    "andi	a0, a0, -256",
    "47:", // .LBB5_4: in Loop: Header=BB5_1 Depth=1
    "lw	a2, 4(a3)",
    "beqz	a2, 49f",
    // in Loop: Header=BB5_1 Depth=1
    "li	a1, 0",
    "lw	a3, 8(sp)", // 4-byte Folded Reload
    "48:", // .LBB5_6: Parent Loop BB5_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "srl	a4, s1, a1",
    "addi	a1, a1, 1",
    "andi	a4, a4, 1",
    "xor	a4, a4, s0",
    "snez	a4, a4",
    "addi	a4, a4, -1",
    "and	a4, a4, a0",
    "sw	a4, 0(a3)",
    "addi	a3, a3, 4",
    "bne	a2, a1, 48b",
    "49:", // .LBB5_7: in Loop: Header=BB5_1 Depth=1
    "lui	a0, %hi(59f)",
    "lw	a0, %lo(59f)(a0)",
    "lw	a1, 12(sp)", // 4-byte Folded Reload
    "jal	ra, 21b",
    "li	a0, 0",
    "li	a2, 40",
    "50:", // .LBB5_8: Parent Loop BB5_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB5_9 Depth 3
    "li	a1, 667",
    "51:", // .LBB5_9: Parent Loop BB5_1 Depth=1
    // Parent Loop BB5_8 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 51b",
    // in Loop: Header=BB5_8 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, a2, 50b",
    // in Loop: Header=BB5_1 Depth=1
    "jal	ra, 54f",
    "jal	ra, 41b",
    "li	a0, 0",
    "li	a2, 45",
    "52:", // .LBB5_12: Parent Loop BB5_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB5_13 Depth 3
    "li	a1, 667",
    "53:", // .LBB5_13: Parent Loop BB5_1 Depth=1
    // Parent Loop BB5_12 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 53b",
    // in Loop: Header=BB5_12 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, a2, 52b",
    // in Loop: Header=BB5_1 Depth=1
    "jal	ra, 54f",
    "lw	a2, 16(sp)", // 4-byte Folded Reload
    "addi	a2, a2, 1",
    "lui	a3, %hi(59f)",
    "addi	a3, a3, %lo(59f)",
    "li	a0, 3",
    "bne	a2, a0, 45b",
    "lw	ra, 28(sp)", // 4-byte Folded Reload
    "lw	s0, 24(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	s1, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw s1, 24(sp)",
    "addi sp, sp, 4",
    "addi	sp, sp, 32",
    "ret",
    "54:", // drain_fifo1: @drain_fifo1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bgez	a0, 58f",
    "lui	a0, %hi(61f)",
    "li	a1, 1",
    "55:", // .LBB6_2: =>This Inner Loop Header: Depth=1
    // --- inline asm begin ---
    "mv	a2, x17",
    // --- inline asm end ---
    "bltz	a2, 56f",
    // in Loop: Header=BB6_2 Depth=1
    "srli	a3, a2, 30",
    "beqz	a3, 57f",
    // in Loop: Header=BB6_2 Depth=1
    "zext.b	a2, a2",
    "sw	a2, %lo(61f)(a0)",
    "j	57f",
    "56:", // .LBB6_5: in Loop: Header=BB6_2 Depth=1
    // --- inline asm begin ---
    "mv	x18, a1",
    // --- inline asm end ---
    "57:", // .LBB6_6: in Loop: Header=BB6_2 Depth=1
    // --- inline asm begin ---
    "mv	a2, x30",
    // --- inline asm end ---
    "slli	a2, a2, 5",
    "bltz	a2, 55b",
    "58:", // .LBB6_7
    "ret",
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "59:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_count (4 entries, 1 words) ---
    ".p2align 0",
    "60:", // led_count
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: brightness (4 entries, 1 words) ---
    ".p2align 0",
    "61:", // brightness
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_buf (64 entries, 16 words) ---
    ".p2align 0",
    "62:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000" // [60] 0, 0, 0, 0
);
