// AUTOGENERATED CODE on 2026-08-08T10:21:29.760658 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(police_bio_code, BM_POLICE_BIO_START, BM_POLICE_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	33f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // ws2812c_wfi: @ws2812c_wfi
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // main: @main
    "addi	sp, sp, -16",
    "sw	ra, 12(sp)", // 4-byte Folded Spill
    "sw	s0, 8(sp)", // 4-byte Folded Spill
    "sw	s1, 4(sp)", // 4-byte Folded Spill
    "li	a0, 0",
    // --- inline asm begin ---
    "mv	x27, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "lui	a1, %hi(62f)",
    "sw	a0, %lo(62f)(a1)",
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "li	a2, 16",
    "addi	a1, a1, %lo(62f)",
    "bltu	a0, a2, 34f",
    "li	a0, 16",
    "34:", // .LBB3_2
    "sw	a0, 4(a1)",
    "jal	ra, 45f",
    "li	s0, 90",
    "li	s1, 1",
    "35:", // .LBB3_3: =>This Loop Header: Depth=1
    // Child Loop BB3_4 Depth 2
    // Child Loop BB3_5 Depth 3
    // Child Loop BB3_8 Depth 2
    // Child Loop BB3_13 Depth 2
    // Child Loop BB3_14 Depth 3
    // Child Loop BB3_17 Depth 2
    "lui	a1, 12",
    "li	a0, 0",
    "jal	ra, 48f",
    "li	a0, 0",
    "36:", // .LBB3_4: Parent Loop BB3_3 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_5 Depth 3
    "li	a1, 667",
    "37:", // .LBB3_5: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_4 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 37b",
    // in Loop: Header=BB3_4 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, s0, 36b",
    // in Loop: Header=BB3_3 Depth=1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "38:", // .LBB3_8: Parent Loop BB3_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "slli	a0, a0, 5",
    "bgez	a0, 40f",
    // in Loop: Header=BB3_8 Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 39f",
    // in Loop: Header=BB3_8 Depth=2
    // --- inline asm begin ---
    "mv	x18, s1",
    // --- inline asm end ---
    "39:", // .LBB3_11: in Loop: Header=BB3_8 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "j	38b",
    "40:", // .LBB3_12: in Loop: Header=BB3_3 Depth=1
    "li	a0, 1",
    "li	a1, 192",
    "jal	ra, 48f",
    "li	a0, 0",
    "41:", // .LBB3_13: Parent Loop BB3_3 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_14 Depth 3
    "li	a1, 667",
    "42:", // .LBB3_14: Parent Loop BB3_3 Depth=1
    // Parent Loop BB3_13 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 42b",
    // in Loop: Header=BB3_13 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, s0, 41b",
    // in Loop: Header=BB3_3 Depth=1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "43:", // .LBB3_17: Parent Loop BB3_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "slli	a0, a0, 5",
    "bgez	a0, 35b",
    // in Loop: Header=BB3_17 Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 44f",
    // in Loop: Header=BB3_17 Depth=2
    // --- inline asm begin ---
    "mv	x18, s1",
    // --- inline asm end ---
    "44:", // .LBB3_20: in Loop: Header=BB3_17 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "j	43b",
    "45:", // blank: @blank
    "lui	a0, %hi(62f)",
    "addi	a0, a0, %lo(62f)",
    "lw	a2, 4(a0)",
    "beqz	a2, 47f",
    "slli	a1, a2, 2",
    "addi	a0, a0, 8",
    "add	a1, a1, a0",
    "46:", // .LBB4_2: =>This Inner Loop Header: Depth=1
    "sw	zero, 0(a0)",
    "addi	a0, a0, 4",
    "bne	a0, a1, 46b",
    "47:", // .LBB4_3
    "lui	a1, %hi(62f)",
    "lw	a0, %lo(62f)(a1)",
    "addi	a1, a1, %lo(62f)",
    "addi	a1, a1, 8",
    "jal	zero, 21b",
    "48:", // burst: @burst
    "addi	sp, sp, -32",
    "sw	ra, 28(sp)", // 4-byte Folded Spill
    "sw	s0, 24(sp)", // 4-byte Folded Spill
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    "mv	s1, a0",
    "li	a3, 0",
    "lui	a4, %hi(62f)",
    "addi	a4, a4, %lo(62f)",
    "lui	a2, %hi(62f)",
    "lui	a0, 11",
    "addi	a2, a2, %lo(62f)",
    "addi	a4, a4, 8",
    "sw	a4, 4(sp)", // 4-byte Folded Spill
    "addi	a2, a2, 8",
    "sw	a2, 8(sp)", // 4-byte Folded Spill
    "addi	s0, a0, -1366",
    "sw	a1, 12(sp)", // 4-byte Folded Spill
    "49:", // .LBB5_1: =>This Loop Header: Depth=1
    // Child Loop BB5_3 Depth 2
    // Child Loop BB5_5 Depth 2
    // Child Loop BB5_6 Depth 3
    // Child Loop BB5_9 Depth 2
    // Child Loop BB5_13 Depth 2
    // Child Loop BB5_14 Depth 3
    // Child Loop BB5_17 Depth 2
    "sw	a3, 16(sp)", // 4-byte Folded Spill
    "lui	a0, %hi(62f)",
    "addi	a0, a0, %lo(62f)",
    "lw	a2, 4(a0)",
    "beqz	a2, 51f",
    // in Loop: Header=BB5_1 Depth=1
    "li	a0, 0",
    "lw	a4, 4(sp)", // 4-byte Folded Reload
    "50:", // .LBB5_3: Parent Loop BB5_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "srl	a3, s0, a0",
    "addi	a0, a0, 1",
    "andi	a3, a3, 1",
    "xor	a3, a3, s1",
    "snez	a3, a3",
    "addi	a3, a3, -1",
    "and	a3, a3, a1",
    "sw	a3, 0(a4)",
    "addi	a4, a4, 4",
    "bne	a2, a0, 50b",
    "51:", // .LBB5_4: in Loop: Header=BB5_1 Depth=1
    "lui	a0, %hi(62f)",
    "lw	a0, %lo(62f)(a0)",
    "lw	a1, 8(sp)", // 4-byte Folded Reload
    "jal	ra, 21b",
    "li	a0, 0",
    "li	a2, 40",
    "52:", // .LBB5_5: Parent Loop BB5_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB5_6 Depth 3
    "li	a1, 667",
    "53:", // .LBB5_6: Parent Loop BB5_1 Depth=1
    // Parent Loop BB5_5 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 53b",
    // in Loop: Header=BB5_5 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, a2, 52b",
    // in Loop: Header=BB5_1 Depth=1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "li	a1, 1",
    "bgez	a0, 56f",
    "54:", // .LBB5_9: Parent Loop BB5_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 55f",
    // in Loop: Header=BB5_9 Depth=2
    // --- inline asm begin ---
    "mv	x18, a1",
    // --- inline asm end ---
    "55:", // .LBB5_11: in Loop: Header=BB5_9 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 54b",
    "56:", // .LBB5_12: in Loop: Header=BB5_1 Depth=1
    "jal	ra, 45b",
    "li	a0, 0",
    "lw	a1, 12(sp)", // 4-byte Folded Reload
    "lw	a3, 16(sp)", // 4-byte Folded Reload
    "li	a4, 45",
    "57:", // .LBB5_13: Parent Loop BB5_1 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB5_14 Depth 3
    "li	a2, 667",
    "58:", // .LBB5_14: Parent Loop BB5_1 Depth=1
    // Parent Loop BB5_13 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a2, a2, -1",
    "bnez	a2, 58b",
    // in Loop: Header=BB5_13 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, a4, 57b",
    // in Loop: Header=BB5_1 Depth=1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "li	a2, 1",
    "bgez	a0, 61f",
    "59:", // .LBB5_17: Parent Loop BB5_1 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 60f",
    // in Loop: Header=BB5_17 Depth=2
    // --- inline asm begin ---
    "mv	x18, a2",
    // --- inline asm end ---
    "60:", // .LBB5_19: in Loop: Header=BB5_17 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 59b",
    "61:", // .LBB5_20: in Loop: Header=BB5_1 Depth=1
    "addi	a3, a3, 1",
    "li	a0, 3",
    "bne	a3, a0, 49b",
    "lw	ra, 28(sp)", // 4-byte Folded Reload
    "lw	s0, 24(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	s1, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw s1, 24(sp)",
    "addi sp, sp, 4",
    "addi	sp, sp, 32",
    "ret",
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "62:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_count (4 entries, 1 words) ---
    ".p2align 0",
    "63:", // led_count
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_buf (64 entries, 16 words) ---
    ".p2align 0",
    "64:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000" // [60] 0, 0, 0, 0
);
