// AUTOGENERATED CODE on 2026-08-08T10:21:42.253399 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(rainbow_bio_code, BM_RAINBOW_BIO_START, BM_RAINBOW_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	33f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // ws2812c_wfi: @ws2812c_wfi
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // main: @main
    "addi	sp, sp, -32",
    "sw	ra, 28(sp)", // 4-byte Folded Spill
    "sw	s0, 24(sp)", // 4-byte Folded Spill
    "sw	s1, 20(sp)", // 4-byte Folded Spill
    "li	t1, 0",
    // --- inline asm begin ---
    "mv	x27, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "lui	a1, %hi(52f)",
    "sw	a0, %lo(52f)(a1)",
    // --- inline asm begin ---
    "mv	a2, x17",
    // --- inline asm end ---
    "li	a3, 16",
    "addi	a0, a1, %lo(52f)",
    "bltu	a2, a3, 34f",
    "li	a2, 16",
    "34:", // .LBB3_2
    "sw	a2, 4(a0)",
    "li	a0, 1536",
    "35:", // .LBB3_3: =>This Inner Loop Header: Depth=1
    "sub	a0, a0, a2",
    "addi	t1, t1, 1",
    "bgeu	a0, a2, 35b",
    "li	ra, 0",
    "lui	a1, %hi(52f)",
    "lui	a3, %hi(52f)",
    "addi	a3, a3, %lo(52f)",
    "li	t2, 1",
    "lui	a0, 699051",
    "addi	a1, a1, %lo(52f)",
    "addi	a0, a0, -1365",
    "sw	a0, 16(sp)", // 4-byte Folded Spill
    "addi	a1, a1, 8",
    "sw	a1, 12(sp)", // 4-byte Folded Spill
    "addi	a3, a3, 8",
    "sw	a3, 8(sp)", // 4-byte Folded Spill
    "beqz	a2, 45f",
    "36:", // .LBB3_5
    "lw	a0, 8(sp)", // 4-byte Folded Reload
    "mv	a1, a2",
    "mv	a3, ra",
    "37:", // .LBB3_6: =>This Inner Loop Header: Depth=1
    "li	a5, 1535",
    "mv	a4, a3",
    "bltu	a5, a3, 38f",
    // in Loop: Header=BB3_6 Depth=1
    "li	a4, 1535",
    "38:", // .LBB3_8: in Loop: Header=BB3_6 Depth=1
    "lw	a5, 16(sp)", // 4-byte Folded Reload
    "mulhu	a4, a4, a5",
    "srli	a4, a4, 10",
    "slli	a5, a4, 11",
    "slli	a4, a4, 9",
    "sub	a4, a4, a5",
    "add	a5, a4, a3",
    "srli	a4, a5, 8",
    "zext.b	a5, a5",
    "xori	s1, a5, 255",
    "li	t0, 255",
    "bge	t2, a4, 39f",
    // in Loop: Header=BB3_6 Depth=1
    "li	s0, 2",
    "beq	a4, s0, 40f",
    // in Loop: Header=BB3_6 Depth=1
    "li	s0, 3",
    "beq	a4, s0, 41f",
    // in Loop: Header=BB3_6 Depth=1
    "li	s0, 4",
    "bne	a4, s0, 43f",
    // in Loop: Header=BB3_6 Depth=1
    "li	s0, 0",
    "li	s1, 255",
    "mv	t0, a5",
    "j	44f",
    "39:", // .LBB3_13: in Loop: Header=BB3_6 Depth=1
    "beqz	a4, 42f",
    // in Loop: Header=BB3_6 Depth=1
    "bne	a4, t2, 43f",
    // in Loop: Header=BB3_6 Depth=1
    "li	s0, 255",
    "mv	t0, s1",
    "li	s1, 0",
    "j	44f",
    "40:", // .LBB3_16: in Loop: Header=BB3_6 Depth=1
    "li	t0, 0",
    "li	s0, 255",
    "mv	s1, a5",
    "j	44f",
    "41:", // .LBB3_17: in Loop: Header=BB3_6 Depth=1
    "li	t0, 0",
    "mv	s0, s1",
    "li	s1, 255",
    "j	44f",
    "42:", // .LBB3_18: in Loop: Header=BB3_6 Depth=1
    "mv	s0, a5",
    "mv	s1, a4",
    "j	44f",
    "43:", // .LBB3_19: in Loop: Header=BB3_6 Depth=1
    "li	s0, 0",
    "44:", // .LBB3_20: in Loop: Header=BB3_6 Depth=1
    "lui	a4, 11",
    "mul	s0, s0, a4",
    "li	a4, 176",
    "mul	a5, t0, a4",
    "mul	s1, s1, a4",
    "add	a3, a3, t1",
    "addi	a1, a1, -1",
    "lui	a4, 4080",
    "and	a4, a4, s0",
    "andi	a5, a5, -256",
    "srli	s1, s1, 8",
    "or	a4, a4, a5",
    "sltiu	a5, a3, 1536",
    "addi	a5, a5, -1",
    "or	a4, a4, s1",
    "andi	a5, a5, -1536",
    "sw	a4, 0(a0)",
    "add	a3, a3, a5",
    "addi	a0, a0, 4",
    "bnez	a1, 37b",
    "45:", // .LBB3_21: =>This Loop Header: Depth=1
    // Child Loop BB3_22 Depth 2
    // Child Loop BB3_23 Depth 3
    // Child Loop BB3_26 Depth 2
    "mv	s1, ra",
    "mv	s0, t1",
    "lui	a0, %hi(52f)",
    "lw	a0, %lo(52f)(a0)",
    "lw	a1, 12(sp)", // 4-byte Folded Reload
    "jal	ra, 21b",
    "li	a0, 0",
    "li	a2, 40",
    "46:", // .LBB3_22: Parent Loop BB3_21 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_23 Depth 3
    "li	a1, 667",
    "47:", // .LBB3_23: Parent Loop BB3_21 Depth=1
    // Parent Loop BB3_22 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 47b",
    // in Loop: Header=BB3_22 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, a2, 46b",
    // in Loop: Header=BB3_21 Depth=1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "mv	t1, s0",
    "li	t2, 1",
    "bgez	a0, 50f",
    "48:", // .LBB3_26: Parent Loop BB3_21 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bgez	a0, 49f",
    // in Loop: Header=BB3_26 Depth=2
    // --- inline asm begin ---
    "mv	x18, t2",
    // --- inline asm end ---
    "49:", // .LBB3_28: in Loop: Header=BB3_26 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 48b",
    "50:", // .LBB3_29: in Loop: Header=BB3_21 Depth=1
    "addi	a0, s1, 48",
    "li	a1, 1535",
    "bgeu	a1, a0, 51f",
    // in Loop: Header=BB3_21 Depth=1
    "addi	a0, s1, -1488",
    "51:", // .LBB3_31: in Loop: Header=BB3_21 Depth=1
    "lui	a1, %hi(52f)",
    "addi	a1, a1, %lo(52f)",
    "lw	a2, 4(a1)",
    "mv	ra, a0",
    "bnez	a2, 36b",
    "j	45b",
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "52:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_count (4 entries, 1 words) ---
    ".p2align 0",
    "53:", // led_count
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_buf (64 entries, 16 words) ---
    ".p2align 0",
    "54:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000" // [60] 0, 0, 0, 0
);
