// AUTOGENERATED CODE on 2026-08-12T19:11:42.674214 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(rainbow_bio_code, BM_RAINBOW_BIO_START, BM_RAINBOW_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	33f",
    // --- inline asm end ---
    "21:", // ws2812c: @ws2812c
    "li	a3, 31",
    "bltu	a3, a0, 26f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 26f",
    "li	t0, 0",
    "22:", // .LBB1_3: =>This Loop Header: Depth=1
    // Child Loop BB1_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "23:", // .LBB1_4: Parent Loop BB1_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 24f",
    // in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	25f",
    "24:", // .LBB1_6: in Loop: Header=BB1_4 Depth=2
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "25:", // .LBB1_7: in Loop: Header=BB1_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 23b",
    // in Loop: Header=BB1_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 22b",
    "26:", // .LBB1_9
    "ret",
    "27:", // ws2812c_wfi: @ws2812c_wfi
    "li	a3, 31",
    "bltu	a3, a0, 32f",
    "li	a3, 1",
    "sll	t1, a3, a0",
    "not	a3, t1",
    // --- inline asm begin ---
    "mv	x26, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x24, t1",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "beqz	a2, 32f",
    "li	t0, 0",
    "28:", // .LBB2_3: =>This Loop Header: Depth=1
    // Child Loop BB2_4 Depth 2
    "slli	a4, t0, 2",
    "add	a4, a4, a1",
    "lw	a0, 0(a4)",
    "li	a4, 24",
    "29:", // .LBB2_4: Parent Loop BB2_3 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	x22, t1",
    // --- inline asm end ---
    "slli	a5, a0, 8",
    "bltz	a5, 30f",
    // in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "j	31f",
    "30:", // .LBB2_6: in Loop: Header=BB2_4 Depth=2
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x23, a3",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    // --- inline asm begin ---
    "nop",
    // --- inline asm end ---
    "31:", // .LBB2_7: in Loop: Header=BB2_4 Depth=2
    "addi	a4, a4, -1",
    "slli	a0, a0, 1",
    "bnez	a4, 29b",
    // in Loop: Header=BB2_3 Depth=1
    "addi	t0, t0, 1",
    "bne	t0, a2, 28b",
    "32:", // .LBB2_9
    "ret",
    "33:", // main: @main
    "addi	sp, sp, -48",
    "sw	ra, 44(sp)", // 4-byte Folded Spill
    "sw	s0, 40(sp)", // 4-byte Folded Spill
    "sw	s1, 36(sp)", // 4-byte Folded Spill
    "li	a0, 0",
    // --- inline asm begin ---
    "mv	x27, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "lui	a1, %hi(54f)",
    "sw	a0, %lo(54f)(a1)",
    "addi	a0, a1, %lo(54f)",
    // --- inline asm begin ---
    "mv	a1, x17",
    // --- inline asm end ---
    "sw	a1, 4(a0)",
    // --- inline asm begin ---
    "mv	a1, x17",
    // --- inline asm end ---
    "li	a2, 255",
    "bltu	a1, a2, 34f",
    "li	a1, 255",
    "34:", // .LBB3_2
    "lw	a4, 4(a0)",
    "sw	a1, 8(a0)",
    "li	a0, 17",
    "lui	a2, %hi(54f)",
    "addi	a2, a2, %lo(54f)",
    "bltu	a4, a0, 35f",
    "li	a4, 16",
    "sw	a4, 4(a2)",
    "35:", // .LBB3_4
    "li	a1, 0",
    "li	a0, 1536",
    "36:", // .LBB3_5: =>This Inner Loop Header: Depth=1
    "sub	a0, a0, a4",
    "addi	a1, a1, 1",
    "bgeu	a0, a4, 36b",
    "sw	a1, 32(sp)", // 4-byte Folded Spill
    "li	a3, 0",
    "lui	a1, %hi(54f)",
    "addi	a0, a2, 12",
    "sw	a0, 12(sp)", // 4-byte Folded Spill
    "lui	a0, 699051",
    "addi	a1, a1, %lo(54f)",
    "addi	a0, a0, -1365",
    "sw	a0, 28(sp)", // 4-byte Folded Spill
    "addi	a1, a1, 12",
    "sw	a1, 16(sp)", // 4-byte Folded Spill
    "37:", // .LBB3_7: =>This Loop Header: Depth=1
    // Child Loop BB3_9 Depth 2
    // Child Loop BB3_25 Depth 2
    // Child Loop BB3_26 Depth 3
    // Child Loop BB3_29 Depth 2
    "sw	a3, 24(sp)", // 4-byte Folded Spill
    "sw	a4, 20(sp)", // 4-byte Folded Spill
    "beqz	a4, 46f",
    // in Loop: Header=BB3_7 Depth=1
    "lw	t1, 8(a2)",
    "slli	t0, t1, 8",
    "lw	a3, 12(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	a4, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a4, 24(sp)",
    "addi sp, sp, 4",
    "lw	ra, 24(sp)", // 4-byte Folded Reload
    "38:", // .LBB3_9: Parent Loop BB3_7 Depth=1
    // =>  This Inner Loop Header: Depth=2
    "li	a1, 1535",
    "mv	a0, ra",
    "bltu	a1, ra, 39f",
    // in Loop: Header=BB3_9 Depth=2
    "li	a0, 1535",
    "39:", // .LBB3_11: in Loop: Header=BB3_9 Depth=2
    "lw	a1, 28(sp)", // 4-byte Folded Reload
    "mulhu	a0, a0, a1",
    "srli	a0, a0, 10",
    "slli	a1, a0, 11",
    "slli	a0, a0, 9",
    "sub	a0, a0, a1",
    "add	a0, a0, ra",
    "srli	s0, a0, 8",
    "zext.b	s1, a0",
    "xori	a0, s1, 255",
    "li	t2, 255",
    "li	a1, 1",
    "bge	a1, s0, 40f",
    // in Loop: Header=BB3_9 Depth=2
    "li	a1, 2",
    "beq	s0, a1, 41f",
    // in Loop: Header=BB3_9 Depth=2
    "li	a1, 3",
    "beq	s0, a1, 42f",
    // in Loop: Header=BB3_9 Depth=2
    "li	a1, 4",
    "bne	s0, a1, 44f",
    // in Loop: Header=BB3_9 Depth=2
    "li	a1, 0",
    "li	a0, 255",
    "mv	t2, s1",
    "j	45f",
    "40:", // .LBB3_16: in Loop: Header=BB3_9 Depth=2
    "beqz	s0, 43f",
    // in Loop: Header=BB3_9 Depth=2
    "li	a1, 1",
    "bne	s0, a1, 44f",
    // in Loop: Header=BB3_9 Depth=2
    "li	a1, 255",
    "mv	t2, a0",
    "li	a0, 0",
    "j	45f",
    "41:", // .LBB3_19: in Loop: Header=BB3_9 Depth=2
    "li	t2, 0",
    "li	a1, 255",
    "mv	a0, s1",
    "j	45f",
    "42:", // .LBB3_20: in Loop: Header=BB3_9 Depth=2
    "li	t2, 0",
    "mv	a1, a0",
    "li	a0, 255",
    "j	45f",
    "43:", // .LBB3_21: in Loop: Header=BB3_9 Depth=2
    "mv	a1, s1",
    "mv	a0, s0",
    "j	45f",
    "44:", // .LBB3_22: in Loop: Header=BB3_9 Depth=2
    "li	a1, 0",
    "45:", // .LBB3_23: in Loop: Header=BB3_9 Depth=2
    "mul	s0, a1, t0",
    "mul	s1, t1, t2",
    "mul	a0, t1, a0",
    "lw	a5, 32(sp)", // 4-byte Folded Reload
    "add	a5, a5, ra",
    "addi	a4, a4, -1",
    "lui	a1, 1048560",
    "and	a1, a1, s0",
    "andi	s1, s1, -256",
    "srli	a0, a0, 8",
    "or	a1, a1, s1",
    "sltiu	s1, a5, 1536",
    "addi	s1, s1, -1",
    "or	a0, a0, a1",
    "andi	a1, s1, -1536",
    "sw	a0, 0(a3)",
    "add	ra, a5, a1",
    "addi	a3, a3, 4",
    "bnez	a4, 38b",
    "46:", // .LBB3_24: in Loop: Header=BB3_7 Depth=1
    "mv	s0, a2",
    "lui	a0, %hi(54f)",
    "lw	a0, %lo(54f)(a0)",
    "lw	a1, 16(sp)", // 4-byte Folded Reload
    // ERRATA BUG2 patch: lw	a2, 20(sp) (offset=20,bits[4:0]=20)  // 4-byte Folded Reload
    "addi sp, sp, -4",
    "lw a2, 24(sp)",
    "addi sp, sp, 4",
    "jal	ra, 21b",
    "li	a0, 0",
    "li	a2, 40",
    "lw	a3, 24(sp)", // 4-byte Folded Reload
    "47:", // .LBB3_25: Parent Loop BB3_7 Depth=1
    // =>  This Loop Header: Depth=2
    // Child Loop BB3_26 Depth 3
    "li	a1, 667",
    "48:", // .LBB3_26: Parent Loop BB3_7 Depth=1
    // Parent Loop BB3_25 Depth=2
    // =>    This Inner Loop Header: Depth=3
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "addi	a1, a1, -1",
    "bnez	a1, 48b",
    // in Loop: Header=BB3_25 Depth=2
    "addi	a0, a0, 1",
    "bne	a0, a2, 47b",
    // in Loop: Header=BB3_7 Depth=1
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "mv	a2, s0",
    "bgez	a0, 52f",
    "49:", // .LBB3_29: Parent Loop BB3_7 Depth=1
    // =>  This Inner Loop Header: Depth=2
    // --- inline asm begin ---
    "mv	a0, x17",
    // --- inline asm end ---
    "bltz	a0, 50f",
    // in Loop: Header=BB3_29 Depth=2
    "srli	a1, a0, 30",
    "beqz	a1, 51f",
    // in Loop: Header=BB3_29 Depth=2
    "zext.b	a0, a0",
    "sw	a0, 8(a2)",
    "j	51f",
    "50:", // .LBB3_32: in Loop: Header=BB3_29 Depth=2
    "li	a0, 1",
    // --- inline asm begin ---
    "mv	x18, a0",
    // --- inline asm end ---
    "51:", // .LBB3_33: in Loop: Header=BB3_29 Depth=2
    // --- inline asm begin ---
    "mv	a0, x30",
    // --- inline asm end ---
    "slli	a0, a0, 5",
    "bltz	a0, 49b",
    "52:", // .LBB3_34: in Loop: Header=BB3_7 Depth=1
    "addi	a0, a3, 48",
    "li	a1, 1535",
    "bgeu	a1, a0, 53f",
    // in Loop: Header=BB3_7 Depth=1
    "addi	a0, a3, -1488",
    "53:", // .LBB3_36: in Loop: Header=BB3_7 Depth=1
    "lw	a4, 4(a2)",
    "mv	a3, a0",
    "j	37b",
    // --- rodata: .L_MergedGlobals (4 entries, 1 words) ---
    ".p2align 2",
    "54:", // .L_MergedGlobals
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_count (4 entries, 1 words) ---
    ".p2align 0",
    "55:", // led_count
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: brightness (4 entries, 1 words) ---
    ".p2align 0",
    "56:", // brightness
    ".word 0x00000000", // [0] 0, 0, 0, 0
    // --- rodata: led_buf (64 entries, 16 words) ---
    ".p2align 0",
    "57:", // led_buf
    ".word 0x00000000", // [0] 0, 0, 0, 0
    ".word 0x00000000", // [4] 0, 0, 0, 0
    ".word 0x00000000", // [8] 0, 0, 0, 0
    ".word 0x00000000", // [12] 0, 0, 0, 0
    ".word 0x00000000", // [16] 0, 0, 0, 0
    ".word 0x00000000", // [20] 0, 0, 0, 0
    ".word 0x00000000", // [24] 0, 0, 0, 0
    ".word 0x00000000", // [28] 0, 0, 0, 0
    ".word 0x00000000", // [32] 0, 0, 0, 0
    ".word 0x00000000", // [36] 0, 0, 0, 0
    ".word 0x00000000", // [40] 0, 0, 0, 0
    ".word 0x00000000", // [44] 0, 0, 0, 0
    ".word 0x00000000", // [48] 0, 0, 0, 0
    ".word 0x00000000", // [52] 0, 0, 0, 0
    ".word 0x00000000", // [56] 0, 0, 0, 0
    ".word 0x00000000" // [60] 0, 0, 0, 0
);
